# s = input("please enter your name: ")
# print("hello,", s + "!")
n1 = int(input("Please enter the first number: "))
n2 = int(input("Please enter the second number: "))
print(f"{n1} + {n2} = {n1 + n2}")
